services:
  postgres:
    image: 'postgres:latest'
    container_name: db_mottu
    environment:
      - 'POSTGRES_DB=mottu_web'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
